title: Basic I/O Instruments G60BLE PCB
email: scot.wei@gmail.com
show_downloads: false
description: A Bluetooth/USB double-mode custom keyboard PCB.
github_username: scottywei
theme: jekyll-theme-cayman